version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestTempMainProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestTempMainProject
  gitUsername: PoojaAnandGit
  gitBranch: main
